### PR TITLE
84 unhandled runtime error comes up when refreshing the product page a few times

### PR DESCRIPTION
**Pull request by VitalyyP**
## Summary by CodeRabbit

- **New Features**
	- Updated the `swiper` library to enhance performance and possibly introduce new features.
	- Implemented dynamic loading for the `CartTotalItems` component, improving client-side rendering efficiency.
	- Enhanced the `ProductDetailsPrevSlider` component with improved state handling and streamlined props for better performance.
	- Updated image paths for the `Custom404` component and its associated styles to ensure correct display.

- **Bug Fixes**
	- Improved loading strategy for the `CartTotalItems` component, ensuring it loads correctly without server-side rendering.

- **Tests**
	- Enhanced test robustness for the `Navigation` component by improving asynchronous handling and state assertions.

### CODE REVIEW

**Review by yuramax — DISMISSED** [review]
Looks good to me! 👍

**Review by yuramax — CHANGES_REQUESTED** [review]
@VitalyyP, I still get the error: "Hydration failed..." on `http://localhost:3000/en/shop/cart page` after refreshing the page, please see the screenshot. 

error-hydration-failed

**Review by yuramax — APPROVED** [review]
Great work! 👍 
Good catch on "Not found..." bug and fix! 🔥 
Thanks.

**Review by IhorMasechko — APPROVED** [review]
LGTM!

**Review by Anton-88 — APPROVED** [review]
Great job!

**Pull request merged**
