### PR TITLE
116 set up workflow with the ability to create production releases

### PR DESCRIPTION
**Pull request by VolodymyrVorona**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new GitHub Actions workflow for automated production deployment to Vercel.
	- Added jobs for code linting, unit testing, end-to-end testing, and production deployment.

### CODE REVIEW

**Comment by VolodymyrVorona** [comment]
@coderabbitai review

**Comment by VolodymyrVorona** [comment]
@coderabbitai review

**Review by yuramax — APPROVED** [review]
LGTM! 👍 
Thanks!

**Review by Anton-88 — APPROVED** [review]
LGTM

**Review by IhorMasechko — APPROVED** [review]
LGTM

**Comment by VolodymyrVorona** [comment]
@coderabbitai review

**Pull request merged**
